### ISSUE TITLE
Type error when composing a polymorphic lens

### ISSUE THREAD

**Issue by vtan** [kcsongor/generic-lens#62]
I get a type error when composing a lens defined with `field` for a polymorphic type twice in an expression.
The module below compiles with 1.0.0.1 but not with 1.0.0.2, both on GHC 8.4.3.

```haskell
{-# LANGUAGE DataKinds, DeriveGeneric, TypeApplications #-}
module Lib (example) where
import Data.Generics.Product (field)
import Data.Generics.Internal.VL.Lens (set)
import GHC.Generics (Generic)

data Foo a = Foo { bar :: Bar a } deriving Generic
data Bar a = Bar { x :: a, y :: a } deriving Generic

example :: Foo ()
example =
  set (field @"bar" . field @"x") ()
  . set (field @"bar" . field @"y") ()
  $ Foo{ bar = Bar{ x = (), y = () } }
```

The error is:
```
src/Lib.hs:12:8: error:
    • Couldn't match type ‘generic-lens-1.0.0.2:Data.Generics.Internal.Families.Changing.ReplaceArgs
                             (Foo ())
                             (generic-lens-1.0.0.2:Data.Generics.Internal.Families.Changing.Unify
                                (Bar
                                   (generic-lens-1.0.0.2:Data.Generics.Internal.Families.Changing.P
                                      0
                                      ()
                                      'generic-lens-1.0.0.2:Data.Generics.Internal.Families.Changing.PTag))
                                a0)’
                     with ‘generic-lens-1.0.0.2:Data.Generics.Internal.Families.Changing.ReplaceArgs
                             (Foo ())
                             (generic-lens-1.0.0.2:Data.Generics.Internal.Families.Changing.Unify
                                (Bar
                                   (generic-lens-1.0.0.2:Data.Generics.Internal.Families.Changing.P
                                      0
                                      ()
                                      'generic-lens-1.0.0.2:Data.Generics.Internal.Families.Changing.PTag))
                                b1)’
        arising from a use of ‘field’
      NB: ‘generic-lens-1.0.0.2:Data.Generics.Internal.Families.Changing.ReplaceArgs’ is a non-injective type family
      The type variables ‘a0’, ‘b1’ are ambiguous
    • In the first argument of ‘(.)’, namely ‘field @"bar"’
      In the first argument of ‘set’, namely
        ‘(field @"bar" . field @"x")’
      In the first argument of ‘(.)’, namely
        ‘set (field @"bar" . field @"x") ()’
   |
12 |   set (field @"bar" . field @"x") ()
   |        ^^^^^^^^^^^^

src/Lib.hs:12:8: error:
    • Couldn't match type ‘generic-lens-1.0.0.2:Data.Generics.Internal.Families.Changing.Infer
                             (generic-lens-1.0.0.2:Data.Generics.Internal.Families.Changing.ReplaceArgs
                                (Foo ())
                                (generic-lens-1.0.0.2:Data.Generics.Internal.Families.Changing.Unify
                                   (Bar
                                      (generic-lens-1.0.0.2:Data.Generics.Internal.Families.Changing.P
                                         0
                                         ()
                                         'generic-lens-1.0.0.2:Data.Generics.Internal.Families.Changing.PTag))
                                   b1))
                             a'0
                             b0’
                     with ‘Foo ()’
        arising from a use of ‘field’
      The type variables ‘b1’, ‘a'0’, ‘b0’ are ambiguous
    • In the first argument of ‘(.)’, namely ‘field @"bar"’
      In the first argument of ‘set’, namely
        ‘(field @"bar" . field @"x")’
      In the first argument of ‘(.)’, namely
        ‘set (field @"bar" . field @"x") ()’
   |
12 |   set (field @"bar" . field @"x") ()
   |        ^^^^^^^^^^^^
```
(And the same thing for line 13.)

**Comment by kcsongor** [comment]
Thanks for reporting this, a very subtle bug indeed! Will make a release with the fix soon.
