### ISSUE TITLE
generic-lens-core fails to build on GHC 9.2

### ISSUE THREAD

**Issue by danwdart** [kcsongor/generic-lens#138]
Looks like for some reason GHC 9.2 wants FlexibleContexts - but I don't know of any incompatible changes that might require this.

```
src/Data/Generics/Product/Internal/HList.hs:62:10: error:
    • Non type-variable argument
        in the constraint: Semigroup (HList as)
      (Use FlexibleContexts to permit this)
    • In the instance declaration for ‘Semigroup (HList (a : as))’
   |
62 | instance (Semigroup a, Semigroup (HList as)) => Semigroup (HList (a ': as)) where
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Data/Generics/Product/Internal/HList.hs:65:10: error:
    • Non type-variable argument in the constraint: Monoid (HList as)
      (Use FlexibleContexts to permit this)
    • In the instance declaration for ‘Monoid (HList (a : as))’
   |
65 | instance (Monoid a, Monoid (HList as)) => Monoid (HList (a ': as)) where
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Data/Generics/Product/Internal/HList.hs:146:3: error:
    • Non type-variable argument
        in the constraint: IndexList (n - 1) as' bs' a b
      (Use FlexibleContexts to permit this)
    • In the instance declaration for ‘IndexList n as bs a b’
    |
146 |   ( IndexList (n - 1) as' bs' a b

src/Data/Generics/Product/Internal/Types.hs:153:3: error:
    • Non type-variable argument
        in the constraint: HasTypesUsing ChGeneric s s a a
      (Use FlexibleContexts to permit this)
    • In the instance declaration for ‘HasTypes s a’
    |
153 |   ( HasTypesUsing ChGeneric s s a a
    |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

src/Data/Generics/Product/Internal/Types.hs:182:3: error:
    • Non type-variable argument
        in the constraint: HasTypesOpt ch (Interesting ch a s) s t a b
      (Use FlexibleContexts to permit this)
    • In the instance declaration for ‘HasTypesUsing ch s t a b’
    |
182 |   ( HasTypesOpt ch (Interesting ch a s) s t a b
    |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

src/Data/Generics/Product/Internal/Types.hs:209:3: error:
    • Non type-variable argument
        in the constraint: GHasTypes ch (Rep s) (Rep t) a b
      (Use FlexibleContexts to permit this)
    • In the instance declaration for ‘HasTypesCustom ch s t a b’
    |
209 |   ( GHasTypes ch (Rep s) (Rep t) a b
```

**Comment by danwdart** [comment]
Looks like this happens for all the projects inside this package... having a go at it myself a moment.

**Comment by danwdart** [comment]
Actually I'm still getting these errors, but I'll make that small PR anyway.

[test-case-failures.txt](https://github.com/kcsongor/generic-lens/files/7583629/test-case-failures.txt)

**Comment by raehik** [comment]
I have a PR that adds CI runs for GHC 9.0 and 9.2 & implements @danwdart 's FlexibleContexts fixes. I get some generic-optics-inspection-test failures in GHC 9.0, and various test failures along with some apparently trivial doctest type check failures (seems like type synonyms are expanded?) in GHC 9.2. I haven't taken a good look yet, figured a PR that put together the current changes would be useful.

  * PR https://github.com/raehik/generic-lens/pull/2
  * CI logs https://github.com/raehik/generic-lens/runs/4431782421?check_suite_focus=true (GHC 8.6 failed due to apt timeout)

**Comment by raehik** [comment]
#139 fixes GHC 9.2 support by itself, and my above PR then "fixes" the tests/CI runs (though primarily by disabling a bunch of inspection ones that have changed).

**Comment by kcsongor** [comment]
Fixed in #141
